name: Gen

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch: {}
  
permissions:
  contents: write
  pull-requests: write

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: gen/go.mod
        cache: false

    - name: Gen
      run: |
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        export GITHUB_TOKEN
        go run .
      working-directory: gen

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
