on:
  schedule:
    - cron: '30 5 * * 1,3'
  workflow_dispatch: {}
  
  # This is for testing only. TODO remove this
  push:
    branches: [ "gen-workflow" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: gen/go.mod
        cache: false

    - name: Gen
      run: |
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        export GITHUB_TOKEN
        go run .
      working-directory: gen
